### ISSUE TITLE
online demo is unavailable

### ISSUE THREAD

**Issue by Mactor2018** [open-mmlab/StyleShot#16]
Hello, thanks for your work. However, your demo on huggingface is currently unavailable to access, with `500` error.

**Comment by Jeoyal** [comment]
Hi @Mactor2018, thanks for your interest in our work. The demo on HF often restarts which causes the deployment environment is lost. We are trying to fix this issue. For now, we recommend you to try our demo on [OpenXlab](https://openxlab.org.cn/apps/detail/lianchen/StyleShot).
