### ISSUE TITLE
About training problem with stage 2

### ISSUE THREAD

**Issue by nldhuyen0047** [open-mmlab/StyleShot#19]
Hi, I finished training model with stage 1, but with stage 2, I see the `content_image_file` in `load_data` function, my json file does not have this variable. So the `content_prompt` with the `content_image_file` are similar? Should I need to add this variable in my json file before training in stage 2?

Thank you so much, I look forward to hearing from you soon.

**Comment by Jeoyal** [comment]
`content_image_file` is the content input image that has been processed by contouring. Please follow 
 our [tutorial](https://github.com/open-mmlab/StyleShot/blob/main/DATASET.md) to prepare it (preferably resized to 512x512) and add this variable in json file.

**Comment by nldhuyen0047** [comment]
Thank you so muchhh.

**Comment by Jeoyal** [comment]
:)

**Comment by nldhuyen0047** [comment]
Hi, T_T I have a question that, I do not know how to inference the code after training with new checkpoints, could you please explain to me? 

Thank you so much.

**Comment by nldhuyen0047** [comment]
In my folder, just has model.safetensors, model_1.safetensors, optimizer.bin, random_states_0.pkl and random_state_1.pkl

**Comment by Jeoyal** [comment]
Hope you achieve the results you desire. :)

**Comment by nldhuyen0047** [comment]
Yeah, thank you so much. I hope so ^^.
