### ISSUE TITLE
Confused about the motivation

### ISSUE THREAD

**Issue by chenj02** [open-mmlab/StyleShot#32]
I‘m also trying to achieve style transfer task, but I’m comfused about myself and my motivation--the ControlNet has worked very well at style transfer, so why we still do this?

**Comment by Jeoyal** [comment]
Hi @chenj02 , thank you for your interest in our work.
ControlNet adapts style transfer by shuffling image in pixel wise as style input. This simple design is difficult to extract rich and expressive style representations.
In contrast, StyleShot utilizes a style-aware encoder specifically designed to extract style representations.
Below, we provide the stylized results of ControlNet compared to StyleShot:
![img_v3_02er_ee3e356f-bb72-4e0f-ad02-10c4cc9a100g](https://github.com/user-attachments/assets/7d0e4b1b-e44e-4682-ae76-685a0a89ee69)

**Comment by chenj02** [comment]
thank you very much！！！
