### ISSUE TITLE
slow inference in image driven demo

### ISSUE THREAD

**Issue by zjutkarma** [open-mmlab/StyleShot#34]
Hi, thanks for ur open-source work!

I encountered a problem when I was running the image-driven code, the inference speed is abnormally slow.
The text-driven inference code is smooth.
So wierd, I have no clue.

Could u help me to solve this problem?

**Comment by Jeoyal** [comment]
Hi @zjutkarma, thank you for your interest in our work. It might be caused by the resolution of your input content image being very large.

**Comment by zjutkarma** [comment]
Thank u! I solved it! :)
